# Generated by Django 5.1.1 on 2024-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0006_alter_cita_cliente_alter_cita_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ManyToManyField(to='primeraApp.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ManyToManyField(to='primeraApp.vehiculo'),
        ),
    ]
