# Generated by Django 5.1.1 on 2024-11-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0007_remove_cita_cliente_remove_cita_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
    ]
