# Generated by Django 5.1.1 on 2024-11-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0009_remove_cita_cliente_remove_cita_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primeraApp.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primeraApp.vehiculo'),
        ),
    ]
