# Generated by Django 5.1.1 on 2024-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0011_remove_cita_servicio_cita_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ManyToManyField(to='primeraApp.servicio'),
        ),
    ]
