# Generated by Django 5.1.3 on 2024-11-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0014_remove_empleado_apellido_remove_empleado_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
